#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DroidTemplates.Resource", IsApplication=true)]

namespace DroidTemplates
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_disclosure = DroidTemplates.Resource.Drawable.dialog_disclosure;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_expander_ic_minimized = DroidTemplates.Resource.Drawable.dialog_expander_ic_minimized;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_icon = DroidTemplates.Resource.Drawable.dialog_icon;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_dark = DroidTemplates.Resource.Drawable.dialog_spinner_default_holo_dark;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Drawable.dialog_spinner_default_holo_light = DroidTemplates.Resource.Drawable.dialog_spinner_default_holo_light;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_BoolField = DroidTemplates.Resource.Id.dialog_BoolField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Button = DroidTemplates.Resource.Id.dialog_Button;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_DisclosureField = DroidTemplates.Resource.Id.dialog_DisclosureField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_HtmlField = DroidTemplates.Resource.Id.dialog_HtmlField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageLeft = DroidTemplates.Resource.Id.dialog_ImageLeft;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ImageRight = DroidTemplates.Resource.Id.dialog_ImageRight;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelField = DroidTemplates.Resource.Id.dialog_LabelField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelPercentageField = DroidTemplates.Resource.Id.dialog_LabelPercentageField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_LabelSubtextField = DroidTemplates.Resource.Id.dialog_LabelSubtextField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Panel = DroidTemplates.Resource.Id.dialog_Panel;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_RadioButtonList = DroidTemplates.Resource.Id.dialog_RadioButtonList;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_SliderField = DroidTemplates.Resource.Id.dialog_SliderField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_Spinner = DroidTemplates.Resource.Id.dialog_Spinner;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.dialog_ValueField = DroidTemplates.Resource.Id.dialog_ValueField;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Id.iFormFieldValue = DroidTemplates.Resource.Id.iFormFieldValue;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_achievements = DroidTemplates.Resource.Layout.dialog_achievements;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldleft = DroidTemplates.Resource.Layout.dialog_boolfieldleft;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldright = DroidTemplates.Resource.Layout.dialog_boolfieldright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubleft = DroidTemplates.Resource.Layout.dialog_boolfieldsubleft;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_boolfieldsubright = DroidTemplates.Resource.Layout.dialog_boolfieldsubright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_button = DroidTemplates.Resource.Layout.dialog_button;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_datefield = DroidTemplates.Resource.Layout.dialog_datefield;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_fieldsetlabel = DroidTemplates.Resource.Layout.dialog_fieldsetlabel;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_floatimage = DroidTemplates.Resource.Layout.dialog_floatimage;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_html = DroidTemplates.Resource.Layout.dialog_html;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labeldisclosure = DroidTemplates.Resource.Layout.dialog_labeldisclosure;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldbelow = DroidTemplates.Resource.Layout.dialog_labelfieldbelow;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_labelfieldright = DroidTemplates.Resource.Layout.dialog_labelfieldright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_multiline_labelfieldbelow = DroidTemplates.Resource.Layout.dialog_multiline_labelfieldbelow;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_onofffieldright = DroidTemplates.Resource.Layout.dialog_onofffieldright;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_panel = DroidTemplates.Resource.Layout.dialog_panel;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_root = DroidTemplates.Resource.Layout.dialog_root;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlist = DroidTemplates.Resource.Layout.dialog_selectlist;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_selectlistfield = DroidTemplates.Resource.Layout.dialog_selectlistfield;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textarea = DroidTemplates.Resource.Layout.dialog_textarea;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldbelow = DroidTemplates.Resource.Layout.dialog_textfieldbelow;
			Cirrious.MvvmCross.Dialog.Droid.Resource.Layout.dialog_textfieldright = DroidTemplates.Resource.Layout.dialog_textfieldright;
			Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = DroidTemplates.Resource.String.ApplicationName;
			Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = DroidTemplates.Resource.String.Hello;
			Cirrious.MvvmCross.Plugins.ReflectionEx.Droid.Resource.String.ApplicationName = DroidTemplates.Resource.String.ApplicationName;
			Cirrious.MvvmCross.Plugins.ReflectionEx.Droid.Resource.String.Hello = DroidTemplates.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dialog_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dialog_spinner_default_holo_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dialog_spinner_default_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000f
			public const int MyButton = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int dialog_BoolField = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int dialog_Button = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int dialog_DisclosureField = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int dialog_HtmlField = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int dialog_ImageLeft = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int dialog_ImageRight = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int dialog_LabelField = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int dialog_LabelPercentageField = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int dialog_LabelSubtextField = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int dialog_Panel = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int dialog_RadioButtonList = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int dialog_SliderField = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int dialog_Spinner = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int dialog_ValueField = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int iFormFieldValue = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_html = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_labeldisclosure = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_labelfieldbelow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_labelfieldright = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_multiline_labelfieldbelow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_onofffieldright = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_panel = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_root = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_selectlist = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_selectlistfield = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_textarea = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_textfieldbelow = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_textfieldright = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Main = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
